# Generated by Django 5.2.9 on 2026-01-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_band_like_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='like_new',
        ),
    ]
